# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'trip-search-service'
  heroku.app.name: 'ecovo-trip-search-service'

steps:
- task: InstallSSHKey@0
  inputs:
    hostName: $(id.heroku.host)
    sshPublicKey: $(id.heroku.pub)
    sshKeySecureFile: id.heroku

- script: docker build -f Dockerfile -t $(imageName):$(build.buildId) -t $(imageName):latest .
  displayName: 'Build Docker image'

- script: git remote add heroku ssh://git@heroku.com/$(heroku.app.name).git
  displayName: Add Heroku Remote Git Repository
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: git push heroku HEAD:master
  displayName: Deploy to Heroku
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))